### PR TITLE
Update internal submodule to latest commit on its main branch

### PR DESCRIPTION
**Pull request by JoeStrout**

### CODE REVIEW

**Review by trivoldus28 — APPROVED** [review]

**Comment by supersergiy** [comment]
@trivoldus28 @JoeStrout 
The hiccup here is that we need to sync up the requirements between `pyproject.toml`'s when we update `internal` versions. It's not ideal, but I haven't found a way around it yet. We want both projects to be installable independently to run independent CI's, which drives the need for two pyprojects

**Comment by trivoldus28** [comment]
I'm a bit confused, why does this repo need the extra dependencies if the tests and functionalities don't need them?

**Comment by trivoldus28** [comment]
Maybe put a check if internal exists, install it. If not then don't?

**Comment by supersergiy** [comment]
I'm guessing it's because neither the tests nor the rest of the CI actually import the file in question

**Pull request merged**
