### PR TITLE
feat(training/ROIMaskProcessor): add upstream_pad

### PR DESCRIPTION
**Pull request by trivoldus28**
Also change output mask type to uint8 by default

### CODE REVIEW

**Review by supersergiy — APPROVED** [review]
Looks good! Could you rebase instead of making merge commits next time? otherwise we get a lot of them and they can clutter history in some situations.

**Comment by trivoldus28** [comment]
But I think maybe there should be a more long term solution. In the current setup I don't think we can have more than 2 augments that dynamically modify the index. Maybe save the original index in the current index that the processors can compare?

**Comment by trivoldus28** [comment]
Some errors about docs this time.. I'll wait for that to be resolved first?

**Comment by supersergiy** [comment]
Yup I'm on it

**Comment by supersergiy** [comment]
> But I think maybe there should be a more long term solution. In the current setup I don't think we can have more than 2 augments that dynamically modify the index. Maybe save the original index in the current index that the processors can compare?

Yeah we should think about what to do...

**Pull request merged**
