### PR TITLE
Support mapping as input for most tensor ops

### LINKED ISSUE #447: A decorator that would make `tensor_op`'s work on `dict[str, Tensor]` input
Need `procs` to handle dicts for multi input/output processing.
Decorator approach will reduce code duplication and testing load

### PR DESCRIPTION
**Pull request by nkemnitz**
Should resolve #447.

Only needed it for `rearrange` and `crop` to work with my input/output layer set, though.

### CODE REVIEW

**Comment by supersergiy** [comment]
Very interesting typing problem...
Not sure if we can use overload on a decorator like this to overload the decorated function. Maybe it's more proper to use type variable here to link returned function's input and output type?

**Comment by nkemnitz** [comment]
Have you ever seen a similar pattern elsewhere? It looks a bit clumsy for something that the user could do in a one-liner like `{k: rearrange(v, ...) for k, v in layers.items()}` - just complicated with the cue specs.

**Comment by nkemnitz** [comment]
>Maybe it's more proper to use type variable here to link returned function's input and output type?

I tried that at first, but you have functions (`to_np`) that are meant to change the type.

**Comment by nkemnitz** [comment]
Think that last commit should fix the remaining issues (`Unexpected keyword argument "data" for "interpolate"`). That is a bit annoying, since type hints shouldn't require changes to function calls...

**Comment by nkemnitz** [comment]
Oh, now I think I understand what you mean. `support_dict` always only takes a `Callable` that expects a `TensorTypeVar` as input, and the `wrapper` function inside is the overloaded one that returns a `Callable` whose output depends on whether the input is a mapping or not... I can let mypy do the painful work of calculating the return type... but I don't think we can actually annotate anything as `Overload` yet(?):

```python
def supports_dict(func: Callable[Concatenate[TensorTypeVar, P], ReturnTensorTypeVar]):
    @overload
    def wrapper(
        data: Mapping[HashableTypeVar, TensorTypeVar], *args: P.args, **kwargs: P.kwargs
    ) -> dict[HashableTypeVar, ReturnTensorTypeVar]:
        ...

    @overload
    def wrapper(data: TensorTypeVar, *args: P.args, **kwargs: P.kwargs) -> ReturnTensorTypeVar:
        ...

    def wrapper(data, *args, **kwargs):

        if isinstance(data, Mapping):
            return {k: func(v, *args, **kwargs) for k, v in data.items()}
        else:
            return func(data, *args, **kwargs)

    reveal_type(wrapper)
    return wrapper
```
```bash
Revealed type is "Overload(def [HashableTypeVar <: typing.Hashable] (data: typing.Mapping[HashableTypeVar`-4, TensorTypeVar`-1], *P.args, **P.kwargs) -> builtins.dict[HashableTypeVar`-4, ReturnTensorTypeVar`-3], def (data: TensorTypeVar`-1, *P.args, **P.kwargs) -> ReturnTensorTypeVar`-3)"
```

**Comment by supersergiy** [comment]
How about just using `TypeVar`, and not using the decorator for `to_np`, `to_torch`, `as_type`?

**Comment by nkemnitz** [comment]
>How about just using TypeVar, and not using the decorator for to_np, to_torch, as_type?
Fine with me, but it doesn't seem to cause harm.

Bigger issue now is that the typecheckers are completely happy with `convert.to_float32("Hello")` and I don't understand why.

**Comment by supersergiy** [comment]
Does that happen if you remove the `overlaod` form the decorator?

**Comment by nkemnitz** [comment]
Good idea. Still happens when I remove the overloads from `wrapper`. But works as expected if I additionally set the return type of `supports_dict`...
So likely mypy _needs_ the return type of the outer function... which I don't know how to provide with overload

**Comment by supersergiy** [comment]
I didn't mean your new solution with `wrapper`, I mean the original decorator `supports_dict` -- fully annotate it with a type variable that can take on either Torch | NDArray or dict of them, and returns the same type

**Comment by supersergiy** [comment]
Perhaps we should just meet tomorrow to discuss?

**Comment by supersergiy** [comment]
@nkemnitz https://github.com/python/mypy/issues/16137 doesn't seem to be getting any attention, so I extended our mypy plugin to handle your `supports_dict` function. I think we're good to merge now. Sorry this took so long -- typing system bugs are always extra painful

**Review by supersergiy — APPROVED** [review]

**Pull request merged**
