### PR TITLE
fix(aug/misalignment): change to px displacement

### PR DESCRIPTION
**Pull request by trivoldus28**
Other changes:
- fixed & cleaned up typing (e.g., torch.Tensor→TensorTypeVar, list→Sequence)
- add saving misalignment metadata for downstream operations

### CODE REVIEW

**Comment by trivoldus28** [comment]
The fix for above error is currently in https://github.com/ZettaAI/internal/pull/40

**Comment by supersergiy** [comment]
Can we close https://github.com/ZettaAI/zetta_utils/pull/611 after this?

**Review by supersergiy — APPROVED** [review]
Looks good

**Comment by trivoldus28** [comment]
Yea I'm pretty sure everything in #611 is in here

**Pull request merged**
