### PR TITLE
feat: Vec3D is hashable

### PR DESCRIPTION
**Pull request by dodamih**

### CODE REVIEW

**Comment by supersergiy** [comment]
Isn't it dangerous to have it both hashable and mutable?

**Comment by dodamih** [comment]
It is dangerous, but I think it's okay for our use cases. I could add a warning as I suggested today if you think it's necessary (first time hash is called, keep track of what the value was at that point).

**Comment by supersergiy** [comment]
I think somebody can get really screwed over if we do this. Why don't we just deprecate `__setitem__` to stay on the safe side?

**Comment by dodamih** [comment]
`__setitem__` isn't the issue as much as `attrs.frozen` not working with `init=False`, meaning that using numpy numbers directly might not work.

**Comment by supersergiy** [comment]
But at the very least we should disable `__setitem__`, right?

**Comment by supersergiy** [comment]
What does `attrs` not like with `frozen(init=False)`?

**Comment by dodamih** [comment]
You cannot do things like `self.x = var` when you have `attrs.frozen` because it overwrites the `setattr`: https://github.com/python-attrs/attrs/issues/113

**Comment by supersergiy** [comment]
Does `object.setattr` trick not work? https://github.com/ZettaAI/zetta_utils/blob/bb10f113b8858754253458d801902b4ccbeac34d/zetta_utils/geometry/bbox_strider.py#L59

**Comment by dodamih** [comment]
Oh, that trick did work. Strange.

**Comment by dodamih** [comment]
Should be ready now.

**Review by supersergiy — CHANGES_REQUESTED** [review]
fails CI

**Review by supersergiy — APPROVED** [review]

**Review by supersergiy — APPROVED** [review]

**Pull request merged**
